### ISSUE TITLE
Updated assets for docs website(renative template)

### ISSUE THREAD

**Issue by pavjacko** [renative-org/renative-website#13]
- scrshots of @rnv/template-starter
- vid recording of @rnv/template-starter
- [x] android
- [x] androidtv
- [x] androidwear
- [x] firetv
- [x] web
- [x] webtv
- [x] webos
- [x] ios
- [x] tvos
- [x] windows
- [x] linux
- [x] tizen
- [x] tizenwatch
- [x] macos
- [x] #17
- [x] kaios

## Related issues

- https://github.com/flexn-io/renative/issues/1456

**Comment by Marius456** [comment]
I can't run `npx rnv run` in new project which created with `@flexn/create-template-starter` template.
<img width="1067" alt="image" src="https://github.com/flexn-io/renative-docs/assets/47567608/81386bed-4980-4191-a21f-e3be22f175e0">
<img width="778" alt="image" src="https://github.com/flexn-io/renative-docs/assets/47567608/ef29e425-0dae-4b99-b988-24cde4edd612">
