### ISSUE TITLE
Make sure we have correct dependencies in renative wiki

### ISSUE THREAD

**Issue by mihaiblaga89** [renative-org/renative-website#6]
Bootstrapping on a new laptop fails because of node-canvas depencencies pixman, cairo and pango from brew. Make sure they are part of the wiki

**Comment by pavjacko** [comment]
command to be used:

```
brew install pkg-config cairo pango libpng jpeg giflib librsvg
```

**Comment by pauliusguzas** [comment]
@mihaiblaga89 what's url of v1 wiki?

**Comment by pauliusguzas** [comment]
@ElenaDiachenko cc

**Comment by mihaiblaga89** [comment]
@pauliusguzas https://github.com/flexn-io/wiki/blob/main/setup/environment.md here's the PR for the change

**Comment by pauliusguzas** [comment]
@mihaiblaga89 should that be under level2? not level1?

**Comment by mihaiblaga89** [comment]
lvl2 is renative developer, lvl1 is generic
